### ISSUE TITLE
flume的source端如何配置

### ISSUE THREAD

**Issue by xiazi123** [cwtree/flume-filemonitor-source#2]
你这个项目如何引用，用eclipse打成jar包导入到flume的lib目录下行吗？还有就是该如何配置文件，能否给个例子，万分感谢啊。。。

**Comment by cwtree** [comment]
建个工程，导入这个项目，打包成jar，放到你的flume的lib下，直接配置用即可

**Comment by xiazi123** [comment]
[hadoop@h71 conf]$ cat chiwei.conf 
a1.sources.r1.type=org.apache.flume.chiwei.filemonitor.FileMonitorSource
a1.sources.r1.channels=c1
a1.sources.r1.file=/home/hadoop/example/file/bizlogic.log
a1.sources.r1.positionDir=/home/hadoop
直接这样配置后启动bin/flume-ng agent -c . -f conf/chiwei.conf -n a1 -Dflume.root.logger=INFO,console命令吗？你这个如何实现的端点续传功能啊，能达到tail -F命令的效果吗

**Comment by cwtree** [comment]
可以的，按字节传输的，你可以试试

**Comment by xiazi123** [comment]
额，我那样配置后启动flume没有反应啊。我这样配置后倒是可以打印出数据，并且结束flume进程后position.log有变化。以下是我的配置：
a1.sources = r1
a1.sinks = k1
a1.channels = c1

a1.sources.r1.type=org.apache.flume.chiwei.filemonitor.FileMonitorSource
a1.sources.r1.channels=c1
a1.sources.r1.file=/home/hadoop/example/file/bizlogic.log
a1.sources.r1.positionDir=/home/hadoop

a1.sinks.k1.type = logger

a1.channels.c1.type = memory
a1.channels.c1.capacity = 1000
a1.channels.c1.transactionCapacity = 100

a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1
本来想以flume的exec中的tail -F命令来动态实时抽取数据到hbase中，并且在网上找到了可以直接用tail命令tail -n +$(tail -n1 /home/hadoop/n) -F /home/hadoop/data.txt 2>&1 | awk 'ARGIND==1{i=$0;next}{i++;if($0~/^tail/){i=0};print $0;print i >> "/home/hadoop/n";fflush("")}' /home/hadoop/n -来实现断点续传功能，这条命令就可以将flume进程结束的时候记录日志的行数到/home/hadoop/n文件中，奈何flume理解不了这么复杂的命令，可能需要修改exec的源码，这个我不会啊。。。
我不是很理解你的这个运用场景，是能达到动态抽取数据的功能吗，再次重启flume进程的时候是可以从日志上一次抽取的地方再追加吗？
目前我的场景是messages日志在实时增加，我需要把messages中的日志实时抽取到hbase中去，现在缺少断点续传的功能，我该如何结合你这个项目来实现断点续传的功能啊。望赐教。。。

下面这个是我导入hbase中的flume配置：
a1.sources = r1
a1.sinks = k1
a1.channels = c1

a1.sources.r1.type = exec
a1.sources.r1.command = tail -n +0 -F /var/log/messages
a1.sources.r1.port = 44444
a1.sources.r1.host = 192.168.8.71
a1.sources.r1.channels = c1

a1.sinks.k1.type = logger
a1.sinks.k1.type = hbase
a1.sinks.k1.table = messages
a1.sinks.k1.columnFamily = host
a1.sinks.k1.columnFamily = cf
a1.sinks.k1.serializer = com.tcloud.flume.AsyncHbaseLogEventSerializer
a1.sinks.k1.channel = memoryChannel

a1.channels.c1.type = memory
a1.channels.c1.capacity = 1000
a1.channels.c1.transactionCapacity = 100

a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1

**Comment by cwtree** [comment]
它会监测那个文件的变化的，并且周期性的将当前写过的位置记录到position.log文件中，按字节处理的；如果进程挂了，下次重新启动，它会自动按照position.log最后记录的字节位置开始往后写到下游的

**Comment by xiazi123** [comment]
你传入的日志是什么格式的啊？
我传入的是Jan 31 10:24:29 192.168.8.71 hui kernel: External interface ADSL is down
flume配置为：
a1.sources = r1
a1.sinks = k1
a1.channels = c1

a1.sources.r1.type = org.apache.flume.chiwei.filemonitor.FileMonitorSource
a1.sources.r1.channels = c1
a1.sources.r1.file = /home/hadoop/example/file/bizlogic.log
a1.sources.r1.positionDir = /home/hadoop

a1.sinks.k1.type = logger
a1.sinks.k1.type = hbase
a1.sinks.k1.table = messages
a1.sinks.k1.columnFamily = host
a1.sinks.k1.columnFamily = cf
a1.sinks.k1.serializer = com.tcloud.flume.AsyncHbaseLogEventSerializer
a1.sinks.k1.channel = memoryChannel

a1.channels.c1.type = memory
a1.channels.c1.capacity = 1000
a1.channels.c1.transactionCapacity = 100

a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1
但是启动flume进程后报这个错：
12/12/13 10:30:33 INFO instrumentation.MonitoredCounterGroup: Component type: SINK, name: k1 started
12/12/13 10:30:44 ERROR hbase.HBaseSink: Failed to commit transaction.Transaction rolled back.
java.lang.NullPointerException
        at com.tcloud.flume.AsyncHbaseLogEventSerializer.getActions(AsyncHbaseLogEventSerializer.java:99)
        at org.apache.flume.sink.hbase.HBaseSink.process(HBaseSink.java:333)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:724)

**Comment by cwtree** [comment]
你这个错是sink的错，我这个代码写的是source，空指针异常肯定哪里为null了，自己排查下吧；
另外跟监控的日志格式没啥关系，source监控任何文件都行，按字节传输

**Comment by xiazi123** [comment]
那个我找到原因了，你这个source端输出的时候会自动换行，即日志一行后加一个空行，所以和我sink端的正则无法匹配报空值，如果你这个source端输出的时候是一整行的话需要如何修改你FileMonitorSource中的代码呢？
实际输出：
Jan 31 10:24:29 192.168.8.71 hui kernel: External interface ADSL is down

我想要的：
Jan 31 10:24:29 192.168.8.71 hui kernel: External interface ADSL is down

**Comment by cwtree** [comment]
channelProcessor.processEvent(EventBuilder.withBody(readDataBytes,
									headers));
你进去看下这个源码EventBuilder.withBody怎么处理的；
或者你sink的时候加个逻辑，自动忽略空行也行。
