### ISSUE TITLE
监控的文件删除重新生成后该端点续传功能似乎有点力不从心了

### ISSUE THREAD

**Issue by xiazi123** [cwtree/flume-filemonitor-source#3]
你好，想请教一下您有没有遇到该断点续传功能所监控的文件删除后又重新生成后的情况。在实践中我发现当监控的文件正常有内容生成的时候，该功能会正常运行，并且flume进程挂掉的时候position.log也会记录结束时候的字节数。但是当监控的文件删除后，flume的控制台会打印出：
java.io.FileNotFoundException: /home/hadoop/messages (No such file or directory)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:233)
        at org.apache.flume.chiwei.filemonitor.FileMonitorSource$FileMonitorThread.run(FileMonitorSource.java:173)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
的信息，并且卡住不动，将删除的文件再重新创建后再插入新的数据后flume进程又会正常工作。现在的问题是position.log所记录的是文件删除前和重新创建后插入数据的字节数总和，当此时flume进程挂掉后再重新启动后，由于它所记录的字节数远大于目前文件的字节数，当该文件再插入数据后，它会将该文件的内容全部读取从而达不到断点续传的功能。这个时候flume进程再挂掉且监控的文件不删除一直存在的话，再次启动它才又会达到端点续传的功能。
       实际应用中我想到了Linux的日志轮询，如果我用该功能监控Linux本地的/var/log/messages日志的话，日志轮询功能就会定期将该文件改名为message.1并且再创建新的空messages文件。我想的是能不能修改下你的代码达到当监控的文件删除再重新创建的时候position.log所记录的字节数能够重新记录（在flume进程不挂掉的情况下），虽然我有这个想法，但不知道如何从代码中入手，或者您是否有更好的方法，还望赐教，不胜感激。

**Comment by cwtree** [comment]
恩，欢迎你提交PR，我们共同维护
